### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Maxmudjon** [athombv/apps-sdk-issues#121]
How to increase limit on Homey API for makeCapabilityInstance()

(device.setMaxListeners(Infinity) did not help)

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect_error listeners added. Use emitter.setMaxListeners() to increase limit
    at /node_modules/athom-api/dist/index.js:1:1257420
    at o.value (/node_modules/athom-api/dist/index.js:1:1257700)
    at o.value (/node_modules/athom-api/dist/index.js:1:1207024)
    at o.value (/node_modules/athom-api/dist/index.js:1:1257768)
    at o.value (/node_modules/athom-api/dist/index.js:1:1257999)
    at /node_modules/athom-api/dist/index.js:1:1213238
    at new Promise (<anonymous>)
    at new e (/node_modules/athom-api/dist/index.js:1:28205)
    at o.value (/node_modules/athom-api/dist/index.js:1:1207024)
    at o.value (/node_modules/athom-api/dist/index.js:1:1257768)
    at o.value (/node_modules/athom-api/dist/index.js:1:1257999)
    at /node_modules/athom-api/dist/index.js:1:1213238
    at new Promise (<anonymous>)
    at new e (/node_modules/athom-api/dist/index.js:1:28205)
    at o.<anonymous> (/node_modules/athom-api/dist/index.js:1:1213188)
    at x (/node_modules/athom-api/dist/index.js:1:346389) {
  name: 'MaxListenersExceededWarning',
  emitter: o {
    _security: { oauth2: [Object] },
    token: {
      name: 'homey_auth',
      isQuery: false,
      value: '04d1f67b-3657-481e-a71e-1bdf054eec3a:42da3928-1b17-4681-a190-d782d33c895b:01de19ff148798a35bd3cd1515664132246821e3'
    },
    _caches: {
      'HomeyAPI.ManagerDevices.Device': [t],
      'HomeyAPI.ManagerDevices.Capability': [t]
    },
    _pendingCalls: {},
    refreshSessionToken: [Function],
    _baseUrl: 'http://localhost:80',
    _basePath: '/api/manager/devices',
    _eventNS: '/realtime/manager/devices/',
    _eventURI: 'homey:manager:devices',
    authorizationUrl: '',
    managerName: 'ManagerDevices'
  },
  type: 'connect_error',
  count: 11
}

**Comment by WeeJeWel** [comment]
It's an internal EventEmitter so for now you can't. Luckily it's just a warning, which is there for good purposes :)
