### ISSUE TITLE
SDK3 createwebhook does not recognise .on event

### ISSUE THREAD

**Issue by dudz40** [athombv/apps-sdk-issues#130]
let rachioWebhook = this.homey.cloud.createWebhook(this.settings.webhookId, this.settings.webhookSecret, this.data);
            rachioWebhook
                .on('message', args => {
                    this.triggerDevicesFromWebhook(args.body)
                })

gives:

Unable to initialize app TypeError: rachioWebhook.on is not a function
    at RachioApp.onInit (/app.js:18:18)
    at SDK._initApp (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:284:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SDK.createClient (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:172:5)

**Comment by WeeJeWel** [comment]
You should await createWebhook. Now you're trying to call .on() on a Promise. :)
