### ISSUE TITLE
Exception in manager/settings.js

### ISSUE THREAD

**Issue by runely** [athombv/apps-sdk-issues#155]
I have received two of these crash reports for my app [IcalCalendar](https://github.com/runely/calendar-homey). Both for firmware 4.2.0

The only information in the stack trace that points to my app is 'uris' which is the key i have for one of the settings. I have never experienced this exception when debugging or running the production app.

```javascript
/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/settings.js:1
"use strict";const fs=require("fs"),path=require("path"),Homey=require("homey");class ManagerSettings extends Homey.Manager{__onInit(){this._updateSettingsTimeout=void 0,this._writing=!1,this.__client.emitSystem("getSettings").then(t=>{this._settings=t,this.__ready()}).catch(t=>{this.error(t),this._settings={},this._updateSettings(),this.__ready()}),this.__client.on("settings.get",this._onSettingsGet.bind(this)),this.__client.on("settings.set",this._onSettingsSet.bind(this)),this.__client.on("settings.unset",this._onSettingsUnset.bind(this))}_onSettingsGet(t,e){return!1===t.name?e(null,this._settings):e(null,this.get(t.name))}_onSettingsSet(t,e){try{return this.set(t.name,t.value),e(null,this.get(t.name))}catch(t){return e(t)}}_onSettingsUnset(t,e){try{return this.unset(t.name,t.value),e(null)}catch(t){return e(t)}}getKeys(){return Object.keys(this._settings)}get(t){if("string"!=typeof t)throw new Error("Cannot get setting, 

TypeError: Cannot read property 'uris' of undefined
    at ManagerSettings.get (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/settings.js:1:998)
    at ManagerSettings._onSettingsGet (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/settings.js:1:622)
    at /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1284
    at Array.forEach (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1261)
    at process.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by runely** [comment]
There's also been one crash report for firmware 4.0.0.

```javascript
/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/settings.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";const fs=require("fs"),path=require("path"),Homey=require("homey");class ManagerSettings extends Homey.Manager{__onInit(){this._updateSettingsTimeout=void 0,this._writing=!1,this.__client.emitSystem("getSettings").then(t=>{this._settings=t,this.__ready()}).catch(t=>{this.error(t),this._settings={},this._updateSettings(),this.__ready()}),this.__client.on("settings.get",this._onSettingsGet.bind(this)),this.__client.on("settings.set",this._onSettingsSet.bind(this)),this.__client.on("settings.unset",this._onSettingsUnset.bind(this))}_onSettingsGet(t,e){return!1===t.name?e(null,this._settings):e(null,this.get(t.name))}_onSettingsSet(t,e){try{return this.set(t.name,t.value),e(null,this.get(t.name))}catch(t){return e(t)}}_onSettingsUnset(t,e){try{return this.unset(t.name,t.value),e(null)}catch(t){return e(t)}}getKeys(){return Object.keys(this._settings)}get(

TypeError: Cannot read property 'uris' of undefined
    at ManagerSettings.get (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/settings.js:1:1060)
    at ManagerSettings._onSettingsGet (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/settings.js:1:684)
    at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1346)
    at Array.forEach (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1323)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

And there's been two crash reports for firmware 5.0.0-rc.38.

```javascript
/opt/homey-client/node_modules/homey-apps-sdk-v2/manager/settings.js:72
    if (typeof this._settings[key] === 'undefined') { return null; }
                             ^

TypeError: Cannot read property 'uris' of undefined
    at ManagerSettings.get (/opt/homey-client/node_modules/homey-apps-sdk-v2/manager/settings.js:72:30)
    at ManagerSettings._onSettingsGet (/opt/homey-client/node_modules/homey-apps-sdk-v2/manager/settings.js:35:32)
    at HomeyClient._onMessage (/opt/homey-client/node_modules/homey-apps-sdk-v2/lib/HomeyClient.js:122:9)
    at IPCSocket.emit (events.js:311:20)
    at IPCSocket._handleMessage (/opt/homey-client/system/lib/IPCSocket.js:1:858)
    at process.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by tjallingt** [comment]
Thanks for reporting! It appears that somehow the setting page is requesting settings while the app is not yet ready and this is causing a crash.

I made sure that this will no longer cause crashes in Homey 5.0 (in SDK v2 and v3), instead the settings page will show a popup indicating that the app is not ready.

Unfortunately we cannot backport this fix to older Homey versions, so its possible you might see these issues for a while :(

**Comment by runely** [comment]
Thank you for letting us know :)
