### ISSUE TITLE
Cronjobs not working

### ISSUE THREAD

**Issue by bvdbos** [athombv/apps-sdk-issues#16]
Something is wrong in registering Cronjobs (OpenWeatherMaps in this case)
2018-12-16 09:32:30 [log] [ManagerDrivers] [owmCurrent] [0] device init
2018-12-16 09:32:30 [log] [ManagerDrivers] [owmCurrent] [0] The task has not been registered yet, registering task: bas_25177
2018-12-16 09:32:30 [log] [ManagerDrivers] [owmCurrent] [0] problem with registering cronjob: SQLITE_CONSTRAINT: NOT NULL constraint failed: Cronjob._id

And the rest of the log: not important I think:
2018-12-16 09:32:30 [log] [ManagerDrivers] [owmForecast] [0] device init
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmForecast] [0] The task has not been registered yet, registering task: 5 dagen_39943
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmForecast] [0] problem with registering cronjob: SQLITE_CONSTRAINT: NOT NULL constraint failed: Cronjob._id
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] Received OWM data
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] current condition:
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] undefined
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] Comparing variables before and after current polling interval
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] cloudiness has changed. Previous cloudiness: 75 New cloudiness: 90
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] visibility has changed. Previous visibility: 4700 New visibility: 900
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmForecast] [0] Received OWM data
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmForecast] [0] TypeError: Cannot read property 'weather' of undefined
at weather.getURLHourly.then.then.data (/drivers/owmForecast/device.js:176:65)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] null
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] null
2018-12-16 09:32:31 [log] [ManagerDrivers] [owmCurrent] [0] null

**Comment by WeeJeWel** [comment]
Fixed in v2.0.0-rc.8
