### ISSUE TITLE
Homey app driver create fails for RF device

### ISSUE THREAD

**Issue by gruijter** [athombv/apps-sdk-issues#176]
```
C:\Users\gruij\OneDrive\HomeyDev\com.gruijter.wtlm>homey app driver create
? [en] What is your Driver's Name? ts_ft002
? Do you want to add another language? No
? What is your Driver's ID? ts_ft002
? What is your Driver's Device Class? Sensor (sensor)
? What are your Driver's Capabilities? Battery (measure_battery), Battery alarm (alarm_battery), Dim level (dim), Rain M
eter (meter_rain), Temperature (measure_temperature), Water alarm (alarm_water), Water Meter (meter_water)
? Is this a Z-Wave device? No
? Is this a Zigbee device? No
? Is this a RF device (Infrared, 433 MHz or 868 MHz)? Yes
? Do you want to create a Discovery strategy to find your device automatically in the IP network? No
? Seems good? Yes
✓ Installing npm package (homey-rfdriver)
✓ Installation complete
ENOENT: no such file or directory, open 'C:\Users\gruij\OneDrive\HomeyDev\com.gruijter.wtlm\node_modules\homey-rfdriver\.compose\driver\driver.js'
```

**Comment by WeeJeWel** [comment]
Is this an SDK3 app? That's outdated and must be fixed in Homey CLI.

**Comment by gruijter** [comment]
yes, new SDK3 app. Homey CLI v 2.9.7

**Comment by gruijter** [comment]
And on a related note:
```
C:\Users\gruij\OneDrive\HomeyDev\com.gruijter.wtlm>npm install homey-rfdriver
+ homey-rfdriver@3.0.6
added 1 package from 1 contributor in 0.46s

C:\Users\gruij\OneDrive\HomeyDev\com.gruijter.wtlm>homey app run
✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `compose`...
[AppPluginCompose] Added Driver `ts_ft002`
✓ Plugin `compose` finished
✓ Running plugin `rf`...
✓ Installing npm package (homey-rfdriver)
✓ Installation complete
Trace: Error: Invalid version of homey-rfdriver installed. Make sure you have installed v2.0.0 or higher.
    at AppPluginRF.run (C:\Users\gruij\AppData\Roaming\npm\node_modules\homey\lib\AppPluginRF\index.js:44:10)
    at async App.preprocess (C:\Users\gruij\AppData\Roaming\npm\node_modules\homey\lib\App\index.js:221:9)
    at async App.install (C:\Users\gruij\AppData\Roaming\npm\node_modules\homey\lib\App\index.js:157:7)
    at async App.run (C:\Users\gruij\AppData\Roaming\npm\node_modules\homey\lib\App\index.js:106:21)
    at async Object.exports.handler (C:\Users\gruij\AppData\Roaming\npm\node_modules\homey\bin\cmds\app\run.js:27:3)
    at App.preprocess (C:\Users\gruij\AppData\Roaming\npm\node_modules\homey\lib\App\index.js:224:17)
Plugin `rf` did not finish:
Invalid version of homey-rfdriver installed. Make sure you have installed v2.0.0 or higher.

Aborting.
```

**Comment by gruijter** [comment]
And while we are at it... It seems Homey compose doesnt like signals :(

```
{
  "id": "com.gruijter.wtlm",
  "version": "1.0.0",
  "compatibility": ">=5.0.0",
  "sdk": 3,
  "name": {
    "en": "Wireless Tank Level Meter"
  },
  "description": {
    "en": "433MHz liquid level meter "
  },
  "category": [
    "climate"
  ],
  "permissions": [],
  "images": {
    "large": "/assets/images/large.png",
    "small": "/assets/images/small.png"
  },
  "author": {
    "name": "Robin Gruijter",
    "email": "gruijter@hotmail.com"
  },
  "signals": {
    "433": {
      "ts_ft002": {
        "sof": [470, 948, 500, 464, 500, 948, 500, 948],
        "words": [
          [500, 948],
          [500, 464]
        ],
        "interval": 22500,
        "sensitivity": 0.3,
        "repetitions": 2
      }
    }
  }
}
```

```
C:\Users\gruij\OneDrive\HomeyDev\com.gruijter.wtlm>homey app run
✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `compose`...
[AppPluginCompose] Added Driver `ts_ft002`
✓ Plugin `compose` finished
✓ Validating app...
Warning: drivers.ts_ft002 is missing an array 'energy.batteries' because the capability measure_battery is being used. Specifying the type of battery will be required in the future.
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
✓ Pruning dev dependencies...
 — App size: 160.5 KB
✓ Installing Homey App on `Robin's Homey Pro` (https://10-0-0-61.homey.homeylocal.com)...
✓ Homey App `com.gruijter.wtlm` successfully installed
✓ Running `com.gruijter.wtlm`, press CTRL+C to quit
 — Profile your app's performance at https://go.athom.com/app-profiling?homey=5c4968afb1b00f14323059f6&app=com.gruijter.wtlm
─────────────── Logging stdout & stderr ───────────────
2021-03-02 12:13:01 [log] [MyApp] MyApp has been initialized
Unable to initialize app Error: Invalid signal: 433.ts_ft002. Make sure it is defined in your app.json
    at ManagerRF._validateSignal (/opt/homey-client/node_modules/homey-apps-sdk-v3/manager/rf.js:78:11)
    at ManagerRF.getSignal433 (/opt/homey-client/node_modules/homey-apps-sdk-v3/manager/rf.js:90:10)
    at MyApp.onInit (/app.js:13:36)
    at SDK._initApp (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:284:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async SDK.createClient (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/SDK.js:172:5)

--- INFO: com.gruijter.wtlm has been killed ---
```

**Comment by WeeJeWel** [comment]
When using Homey Compose, please put your signals in `./homeycompose/signals/<freq>/<id>.json`.

**Comment by tjallingt** [comment]
This should be fixed in the latest Homey CLI release, thanks for reporting!
