### ISSUE TITLE
Problem with retreiving device information rc9

### ISSUE THREAD

**Issue by daneedk** [athombv/apps-sdk-issues#19]
After updating to rc9 it is no longer possible to retrieve device information. This code:
```
        let allDevices = await this.getDevices();

        for (let device in allDevices) {
            this.addDevice(allDevices[device])
        };

    addDevice(device) {
        if ( device.data.id === 'sMode' ) {
        .......
```
produces this error:

```
(node:2728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Heimdall.addDevice (/app.js:147:26)
    at Heimdall.enumerateDevices (/app.js:140:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:2728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```line 147 --> if ( device.data.id === 'sMode' ) { ```

**Comment by SailingDuck** [comment]
Have trouble to after readding better logic devices too. Every last added device shows a triangle. If you add a new device the previous triangle goes away.

**Comment by WeeJeWel** [comment]
I'll fix this in rc.10

**Comment by WeeJeWel** [comment]
Update: this is fixed in rc.12
