### ISSUE TITLE
mDNS - Missing libdns_sd.so.1

### ISSUE THREAD

**Issue by TheRealLink** [athombv/apps-sdk-issues#212]
I tried implementing an AppleTV driver for Homey. On pairing, the used package (node-appletv) relies heavily on mdns.

As soon as I call any mdns functionality, the static lib can not be found:

`[err] 2021-06-08 21:00:48 [ManagerDrivers] Error: libdns_sd.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.homeyRequire [as require] (/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js:12:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)`

**Comment by WeeJeWel** [comment]
Sorry, but you can't use native modules in Homey apps.

Try using ManagerDiscovery or mdns-js.
