### ISSUE TITLE
Possible false report of unhandledRejection

### ISSUE THREAD

**Issue by AdyRock** [athombv/apps-sdk-issues#250]
Another crash that makes no sense to me:
```
Note: this e-mail is sent because an unhandledRejection occurred in your app. Make sure to catch all errors, this might crash your app in the future. Stack trace attached below:

  Error: BLE Timeout
    at Remote Process
    at HomeyClient.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/HomeyClient.js:1:312)
    at Object.emit (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/manager/ble.js:130:32)
    at BlePeripheral.discoverServices (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1114)
    at BlePeripheral.getService (/opt/homey-client/system/manager/ManagerApps/AppProcess/node_modules/homey-apps-sdk-v3/lib/BlePeripheral.js:1:1544)
    at BotBLEDevice._operateBotLoop (/drivers/bot_ble/device.js:232:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BotBLEDevice._operateBot (/drivers/bot_ble/device.js:175:28)
```
      
This is the first section referenced by the last line (line arrowed):
```
try
            {
--> 175         response = await this._operateBotLoop(name, bytes);
                if (response.status && (response.status === true))
                {
                    this.homey.app.bleBusy = false;
                    this.homey.app.updateLog(`Command complete for ${name}`);
                    this.sendingCommand = false;
                    return;
                }
            }
            catch (err)
            {
                this.homey.app.updateLog(`_operateBot error: ${name} : ${this.homey.app.varToString(err)}`, 0);
            }
```
and this is the second section referenced by third from bottom line:
```
try
            {
                this.homey.app.updateLog(`Getting service for ${name}`);
--> 232                const bleService = await blePeripheral.getService('cba20d00224d11e69fb80002a5d5c51b');

                this.homey.app.updateLog(`Getting write characteristic for ${name}`);
                const bleCharacteristic = await bleService.getCharacteristic('cba20002224d11e69fb80002a5d5c51b');

                if (parseInt(this.homey.version, 10) >= 6)
                {
                    this.homey.app.updateLog(`Getting notify characteristic for ${name}`);
                    const bleNotifyCharacteristic = await bleService.getCharacteristic('cba20003224d11e69fb80002a5d5c51b');

                    bleNotifyCharacteristic.subscribeToNotifications(data =>
                    {
                        sending = false;
                        returnStatue.notificationData = data;
                        this.homey.app.updateLog(`received notification for ${name}: ${this.homey.app.varToString(data)}`);
                    });
                }

                this.homey.app.updateLog(`Writing data to ${name}`);
                await bleCharacteristic.write(reqBuf);
            }
            catch (err)
            {
                this.homey.app.updateLog(`Catch 2: ${name}: ${this.homey.app.varToString(err)}`);
                sending = false;
                return err;
            }
```
So both section all wrapped up in try catch blocks. Again, running the code on my homey and forcing the errors shows they are handle as expected.

**Comment by jeroenwienk** [comment]
> bleNotifyCharacteristic.subscribeToNotifications(data =>
>                     {
>                         sending = false;
>                         returnStatue.notificationData = data;
>                         this.homey.app.updateLog(`received notification for ${name}: ${this.homey.app.varToString(data)}`);
>                     });

`subscribeToNotifications` is an async method so it might be that one rejecting without being caught since you dont await it. Not sure why it is async though bit odd for a callback function.

**Comment by jeroenwienk** [comment]
> `subscribeToNotifications`

`   * @returns {Promise<void>} - resolves when the subscription is succesful`

**Comment by AdyRock** [comment]
It's not getting that far as it fails to get the service on the arrowed line and throws the exception there. I do await that one, so it is caught by the catch but still shows as an unhandledRejection.
Good to know about the subscribeToNotifications though so I will await that one.
