### ISSUE TITLE
debug module conflict? difference between local install and app install

### ISSUE THREAD

**Issue by irritanterik** [athombv/apps-sdk-issues#32]
I just published the com.internet app and received a lot of app crashes immediatly from auto install users.
One of my dependencies (follow-redirects) depends on module debug.
On local `athom app run` and `athom app install` everything goes well.
On app store install (same version) the app crashes on startup:
``` 
Crash report:

    module.js:550
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/follow-redirects/index.js:7:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```
Module `debug` is in my source: https://github.com/irritanterik/homey-http-request-actions/tree/master/node_modules

**Comment by irritanterik** [comment]
My fault. Did not included proper nested package.json
