### ISSUE TITLE
measure* capabilities are counted as numeric - causing massive logs (flash memory issue)

### ISSUE THREAD

**Issue by RonnyWinkler** [athombv/apps-sdk-issues#331]
If string capabilities are named `measure*` (e.g. text values like compass value 'NO'), every capability changed trigger is causing massive internal log writings to flash memory.

Possible fix:
Code at: `Device#onUpdateCapabilityValue:`
Add a type check for numeric values at:
```
    // Trigger Measure & Meter Flows
    if (capabilityId.startsWith('measure_') || capabilityId.startsWith('meter_')) {
```

**Comment by RobinBol** [comment]
Hi @RonnyWinkler, thanks for raising this issue. Could you elaborate what you mean with "causing massive internal log writings to flash memory"?

**Comment by RonnyWinkler** [comment]
[@Shaarkys](https://athomcommunity.slack.com/team/ULNC24NV6) reported the issue because he recognized a lot of error log lines written to local storage. He already relativized this in Slack - it is only written in MB sizes. But every capability update (setCapabilityValue( )) is causing these log lines writing unneccassary data.
https://athomcommunity.slack.com/archives/C04SUGZ9E/p1704487903837139

He reported the problem because he is generally having problems with too much data being written to his flash memory. I think I mixed these things up but wantet to point to because of the written log data.

**Comment by shaarkys** [comment]
@jeroenwienk @RobinBol  I just found this as closed, did you actually implement any fix please ? 
On latest HP23 with latest firmware, I see this is still spamming a lot - 819 errors just in ~1.5 hour

Parsed journal for "Invalid token type" : 
![log](https://github.com/user-attachments/assets/9a3338c6-1c55-43c3-8e5c-02696033adbe)

Full error example : 

> 2024-12-08 10:49:08.8199 homey-pro[776]: Homey [err][ManagerFlow] HomeyErrorBadRequest: Invalid token type: value. Expected: Number
2024-12-08 10:49:08.8202 homey-pro[776]:     at FlowToken.validateValue (file:///node_modules/@athombv/homey-core/dist/lib/FlowToken.mjs:70:27)
2024-12-08 10:49:08.8204 homey-pro[776]:     at file:///node_modules/@athombv/homey-core/dist/lib/Flow.mjs:354:33
2024-12-08 10:49:08.8205 homey-pro[776]:     at Array.map (<anonymous>)
2024-12-08 10:49:08.8206 homey-pro[776]:     at Flow.run (file:///node_modules/@athombv/homey-core/dist/lib/Flow.mjs:352:62)
2024-12-08 10:49:08.8208 homey-pro[776]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-08 10:49:08.8209 homey-pro[776]:     at async file:///node_modules/@athombv/homey-core/dist/lib/ManagerFlow.mjs:786:17
2024-12-08 10:49:08.8213 homey-pro[776]:     at async Promise.all (index 0)
2024-12-08 10:49:08.8214 homey-pro[776]:     at async ManagerFlow.triggerFlows (file:///node_modules/@athombv/homey-core/dist/lib/ManagerFlow.mjs:784:9) {
2024-12-08 10:49:08.8215 homey-pro[776]:   statusCode: 400

Thank you.

**Comment by shaarkys** [comment]
Seems it's triggered by : 
![battery](https://github.com/user-attachments/assets/07b4d626-1440-40b5-ad01-1518a0b9aefd)

...probably because some of the battery levels/values are (could be) NULL ?

**Comment by RobinBol** [comment]
@shaarkys thanks for bringing this to our attention. I have made some changes that prevents non-numeric values being parsed for the number Flow tokens, which caused the log errors. Should be included in an upcoming release.
