### ISSUE TITLE
Insight data not showing up

### ISSUE THREAD

**Issue by SailingDuck** [athombv/apps-sdk-issues#39]
Busy fixing a bug in creating an insight log I get stuck in at logging data. The function createEntry (https://apps.developer.athom.com/InsightsLog.html) always says:

```
{ Error: log_not_found
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11) message: 'log_not_found', code: 404 }
```

Corresponding code is in the SDK2 branch of Better Logic. Link to the actual function:
https://github.com/PatrickSannes/BetterLogic/blob/SDK2/lib/variablemanager.js#L121

Can someone explain what is going on?

**Comment by WeeJeWel** [comment]
This is due to a bug. Fixed in v2.0.1-rc.3.
