### ISSUE TITLE
Intermittent Permissions Error

### ISSUE THREAD

**Issue by specialcircumstances** [athombv/apps-sdk-issues#55]
**Sometimes** when I am debugging my app using "athom app run" I get the following permissions error:
```

2019-02-14 22:17:12 [log] [Logi] Unregistering All Cron Tasks...
(node:987) UnhandledPromiseRejectionWarning: Error: missing_permission
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
(node:987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:987) UnhandledPromiseRejectionWarning: Error: missing_permission
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
(node:987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:987) UnhandledPromiseRejectionWarning: Error: missing_permission
    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)
    at JSON.parse (<anonymous>)
    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)
    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
(node:987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

The code causing the exception is this:

```
try {
            this.mlog('Unregistering All Cron Tasks...');
            result = await ManagerCron.unregisterAllTasks();
            this.mlog('Done.');
        } catch (err) {
            this.mlog('Unregister All Cron Tasks error : ' + err);
        }

```

The error occurs intermittently, so it looks a bit like a bug.

My app permissions are as follows;

`  "permissions": [ "homey:manager:api", "homey:app:nl.scanno.mqtt" ],`

This is SDKv2, on current stable v2 Homey.

**Comment by WeeJeWel** [comment]
As this never happens elsewhere I am fairly confident that you're making a call somewhere that requires a permission. It's most likely not related to cron as well.

**Comment by WeeJeWel** [comment]
If you provide a clear reproducible path I'll definitely look into it.
