### ISSUE TITLE
Error `Invalid serviceFilter` on BlePeripheral::write

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/apps-sdk-issues#9]
Documentation says:
(async) write(serviceUuid, characteristicUuid, data) → {Buffer}
Shorthand to write to a characteristic for given serviceUuid and characteristicUuid

Name | Type | Description
-- | -- | --
serviceUuid | string | The uuid of the service that has given characteristic
characteristicUuid | string | The uuid of the characteristic that needs to be written to
data | Buffer | The data that needs to be written

But if i try to write with: (2 string constants)
`peripheral.write(DATA_SERVICE_UUID, REALTIME_CHARACTERISTIC_UUID, Buffer.from([0xA0, 0x1F]), false)`

I get an exception:
Error: Invalid serviceFilter, expected Array
    at ManagerBLE.discover (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/ble.js:1:400)
    at HomeyMiFlora.discover (/app.js:61:32)
    at MiFloraSensorDriver._handleUpdateSequence (/lib/MiFloraDriver.js:190:25)
    at MiFloraSensorDriver._updateDevice (/lib/MiFloraDriver.js:126:20)
    at promise.then (/lib/MiFloraDriver.js:109:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by koktaildotcom** [comment]
Same for `BleService::write` (resolves the same function because `BlePeripheral::write` looks a shorthand)

**Comment by koktaildotcom** [comment]
Not reproducible anymore
